        <div class="definitionSystemUser">
        	<div class="memberControl">
        		<ul>
                	<li class="title"><span class="needMark sized-text-normal">角色名稱＊</span></li>
                    <li class="type">
                    	<select class="fullWidth sized-text-1">
                        	<option>管理者</option>
                            <option>客服人員</option>
                        </select>
                    </li>
                    <li><button type="button" class="new"><span class="sized-text-normal">新增角色</span></button></li>
                    <li><button type="button" class="modify"><span class="sized-text-normal">修改角色</span></button></li>
                    <li><button type="button" class="kill"><span class="sized-text-normal">刪除角色</span></button></li>
                </ul>
                <div class="clearFloat"></div>
            </div>
            <p><span class="hor-box-text-normal">角色功能</span></p>
            
            <div class="spacingBlock"></div>
            
            <div class="memberTree hor-box-text-normal">
            樹狀功能開發於此DIV內
            </div>
        </div>