    	<div class="logoAndUser">
        	<h1><img src="../images/cross_think_logo.gif" alt="Cross Think" width="296" height="72"></h1>
            <ul>
            	<li class="name"><span class="sized-text">大聯盟主席曼佛雷德（Rob Manfred）</span></li><!-- 使用者 -->
                <li class="btn"><button type="button"><span class="sized-text">變更密碼</span></button></li><!-- 如果沒有，就不寫入這個LI -->
                <li class="btn"><button type="button"><span class="sized-text">LOG OUT</span></button></li><!-- 如果沒有，就不寫入這個LI -->
            </ul>
        </div>
        <div class="clearFloat"></div>