        <table cellpadding="0" cellspacing="0" class="topMenu item-5">
        	<tr>
            	<td><a href="#" class="hor-box-text"><span>教案管理</span></a></td>
                <td><a href="#" class="hor-box-text"><span>課表範本管理</span></a></td>
                <td><a href="#" class="hor-box-text"><span>使用者管理－客戶</span></a></td>
                <td><a href="#" class="hor-box-text"><span>使用者管理－劍聲</span></a></td>
                <td><a href="#" class="hor-box-text"><span>系統參數</span></a></td>
            </tr>
        </table>