        <table cellpadding="0" cellspacing="0" class="topMenu item-4">
        	<tr>
            	<td>
                	<div class="holder hor-box-text">
                		<span>教師管理</span>
                        <ul class="subLink">
                        	<li><a href="#" class="hor-box-text fixFontSize">教師管理</a></li>
                            <li><a href="#" class="hor-box-text fixFontSize">教師工作進度</a></li>
                        </ul>
					</div>
                </td>
                <td>
                	<div class="holder hor-box-text">
                    	<span>班級與學生管理</span>
                        <ul class="subLink">
                        	<li><a href="#" class="hor-box-text fixFontSize">學生管理</a></li>
                            <li><a href="#" class="hor-box-text fixFontSize">班級管理</a></li>
                        </ul>
                    </div>
				</td>
                <td><a href="#" class="hor-box-text"><span>課程紀錄審核</span></a></td>
                <td>
                	<div class="holder hor-box-text">
                    	<span>系統資訊</span>
                        <ul class="subLink">
                        	<li><a href="#" class="hor-box-text fixFontSize">帳號資訊</a></li>
                            <li><a href="#" class="hor-box-text fixFontSize">變更密碼</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        </table>